README.md, tasks/elasticsearch-scripts.yml, tasks/elasticsearch-templates.yml
This PR addresses the enhancement described in Issue #57.
It uses the Ansible [with_fileglob](http://docs.ansible.com/ansible/playbooks_loops.html#id4) loop with a variable which can be set to a directory on the system which contains scripts or templates. If the variables are not set, then the behavior is unchanged.
I verified this by successfully running the `multi-2x-ubuntu-1404` test. I did not believe it necessary to add a test(s) for this since the relative globs succeeded in the test.
=> Custom scripts templates 57

meta/main.yml
```
$ cat ./requirements.yml
---
- name: elastic.ansible-elasticsearch
src: https://github.com/elastic/ansible-elasticsearch
scm: git
version: master
$ ansible-galaxy install -r ./requirements.yml -p ./roles
- executing: git clone https://github.com/elastic/ansible-elasticsearch elastic.ansible-elasticsearch
- executing: git archive --prefix=elastic.ansible-elasticsearch/ --output=/tmp/tmpQHJSY6.tar master
- extracting elastic.ansible-elasticsearch to ./roles/elastic.ansible-elasticsearch
- elastic.ansible-elasticsearch was installed successfully
Traceback (most recent call last):
File "/usr/bin/ansible-galaxy", line 959, in <module>
main()
File "/usr/bin/ansible-galaxy", line 953, in main
fn(args, options, parser)
File "/usr/bin/ansible-galaxy", line 845, in execute_install …
```
=> path meta/main.yml for fix problem(KeyError) in ansible 1.9.4=< :

.gitignore, .kitchen.yml, Gemfile, README.md, defaults/main.yml, filter_plugins/custom.py, tasks/elasticsearch-config.yml, tasks/elasticsearch-plugins.yml, tasks/elasticsearch-scripts.yml, tasks/elasticsearch-templates.yml, tasks/main.yml, templates/elasticsearch.j2, templates/elasticsearch.yml.j2, templates/init/debian/elasticsearch.j2, templates/systemd/elasticsearch.j2, test/integration/config.yml, test/integration/helpers/serverspec/config_spec.rb, test/integration/helpers/serverspec/multi_spec.rb, test/integration/helpers/serverspec/package_spec.rb, test/integration/helpers/serverspec/standard_spec.rb, test/integration/multi.yml
This pull requests provides the following:
1. Improved plugin support. We now remove and re-install all plugins if the ES version changes (as required by Elasticsearch). Otherwise we only re-install plugins if the user sets the appropriate flag. 
2. Currently we don't dif the the installed vs the requested but this could be added.
3. Fixes known issue with data dirs containing multiple paths and not all being modified.
4. Fixes known issues with init script and more than one node on a machine.
5. Refactors areas using with_items
6. Adds and fixes test issues.
7. Fix for Kitchen CLI issue
8. Only copies init script if required
9. Fix for issues with templates not being copied using default
10. Inconsistent ansible version across images was causing issues types
=> Improved Plugin Support, More Tests, Refactors, Consistent Ansible version

README.md, tasks/elasticsearch-optional-user.yml, tasks/elasticsearch.yml, test/integration/config.yml, test/integration/helpers/serverspec/config_spec.rb
Here's the pull request. :) Per https://github.com/elastic/ansible-elasticsearch/issues/36#issuecomment-198418652
=> For  #36 - Add support for creating optional elasticsearch user and group

README.md
One of the examples didn't have any formatting and was hard to read.
=> Make an example in the README more readable.

vars/Debian.yml, vars/RedHat.yml
If **es_java** variable is set, it will use that as the java package name
instead of the default package.
This can be handy for example when running on Ubuntu 16.04 (which is not yet officially supported).
Example:
```
roles:
- { role: elasticsearch, es_java: "openjdk-8-jre-headless", es_instance_name: "node1" }
```
The specified package must be available in the currently enabled repositories.
=> enable specify java version (package name)

README.md, tasks/elasticsearch-config.yml, tasks/elasticsearch-plugins.yml, tasks/elasticsearch-scripts.yml, tasks/elasticsearch-templates.yml, tasks/elasticsearch.yml, tasks/main.yml
Adding tags to the `tasks/main.yml` allows the user to skip whole sets of tasks from the command line.
```
% ansible-playbook ... ansible-elasticsearch-playbook.yaml --list-tasks
...
tasks:
cyverse.elasticsearch : check-parameters	TAGS: [check]
cyverse.elasticsearch : os-specific vars	TAGS: []
include	TAGS: [java]
include	TAGS: [install]
include	TAGS: [config]
include	TAGS: [scripts]
include	TAGS: [plugins]
include	TAGS: [service]
include	TAGS: [templates]
```
```
% ansible-playbook ... ansible-elasticsearch-playbook.yaml --skip-tags "check,java,install" --list-tasks
...
tasks:
cyverse.elasticsearch : os-specific vars	TAGS: []
include	TAGS: [config]
include	TAGS: [scripts]
include	TAGS: [plugins]
include	TAGS: [service]
include	TAGS: [templates]
```
Note: When you use `--list-tasks` with …
=> Allow for selective command line task execution

defaults/main.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-plugins.yml, tasks/elasticsearch-templates.yml
I have a number of hosts that cannot do direct downloads. This minor change enables simplictic support of custom apt repositories, and also allows the repository signing key url to be set to false for unsigned repositories or for when es_apt_url is a ppa.
I have no rpm distributions to test on, so I have not made the same change to that side of the playbook. It might be worth for someone to do this, though, as it seems like a good idea to move these hardcoded values away from the actual tasks and into the variable defaults.
=> Add support for custom Debian repository; allow repository key to be set to false

tasks/xpack/shield/elasticsearch-shield-file.yml, tasks/xpack/shield/elasticsearch-shield.yml, templates/shield/role_mapping.yml.j2, test/integration/helpers/serverspec/xpack_spec.rb, test/integration/xpack.yml
Resolves https://github.com/elastic/ansible-elasticsearch/issues/155
Suports role mapping through new es_role_mapping variable.  Tests include example but will update docs.
Declare in var syntax e.g.
```
es_role_mapping:
power_user:
- "cn=admins,dc=example,dc=com"
user:
- "cn=users,dc=example,dc=com"
- "cn=admins,dc=example,dc=com"
```
This gets serialized into the yml file.  No validation so relies on the user.
=> Support for Role Mapping

defaults/main.yml, tasks/elasticsearch-Debian.yml
Fix for the issue introduced with the change in https://github.com/elastic/ansible-elasticsearch/pull/170
Changed debian repo from http to https, but existing http repos (from earlier runs) would persist and lead to an duplicate entry warning in apt.
This PR will remove the old http repo, if present.
=> Remove old http repo on debian/ubuntu and use https one.

README.md, templates/elasticsearch.j2
Add the ability to provide custom java options.
I personally use it to define `Djava.io.tmpdir` because our `/tmp` is mounted with `noexec`.
=> Manage ES_JAVA_OPTS in template

filter_plugins/custom.py
fbfbb66d564e5c1696e2803f2310d5d7d866b6e4 added a debug line at the bottom of the custom.py filter which prints a lot of `basic`.
When this line is removed, the output is normal again.
=> Remove debug line

handlers/elasticsearch-templates.yml, handlers/shield/elasticsearch-shield-native.yml
Was causing issues if not bound to localhost and using none default port, as es_api_host/port default to localhost/9200.
@gingerwizard if you got a minute, a review would be nice, as you initially wrote this an I might have missed something.
=> Use network.host and http.port if available for templates and scripts

tasks/xpack/shield/elasticsearch-shield-file.yml
When shield is not installed/disabled, i.e. the _elasticsearch-shield-file.yml_ os not included (due to the `when`-statement), the `with_items` and `with_dict` statements are still evaluated (so Ansible is able to check the `when` for each item in the list/dict).
Unfortunately, the `users_to_remove`, `users_to_add`, and `es_users` variables are not present, so the evaluation of the `with_items` and `with_dict` lists fail.
This PR adds defaults to fix these error situations.
When shield is installed/active the variables are present and the defaults are not used.
Note that I am using Ansible 2.2 (although this issue is also reproducable with ansible 2.1). Maybe Ansible behavior with respect to `include` changed?
=> Prevent Ansible errors when shield is not installed/disabled

handlers/shield/elasticsearch-shield-native.yml, tasks/elasticsearch-scripts.yml, tasks/xpack/shield/elasticsearch-shield-file.yml
Should make https://github.com/elastic/ansible-elasticsearch/issues/167 work.
Added a 15 sec pause before the Native User List command.
Command was run when the realm was not initialized yet, causing the playbook to fail.
Added default value to es_scripts_fileglob. Could fail if undefined.
Closes #187
When a second node is installed, the shield directory and the user* files are not automatically created.
This could cause the role to fail.
- Added check to that shield directory exists
- Added chown -R for the shield directory, as user* files created by the esusers command, belonged to the user ansible is running as.
=> Some fixes for shield related tasks

templates/elasticsearch.j2
Append all `es_java_opts` instead of adding a new line for each `es_java_opts` list entry.
Original:
```
ES_JAVA_OPTS=opt1
ES_JAVA_OPTS=opt2
ES_JAVA_OPTS=opt3
```
With this patch:
```
ES_JAVA_OPTS=opt1 opt2 op3
```
=> Fix setting ES_JAVA_OPTS

tasks/elasticsearch-config.yml, tasks/elasticsearch-parameters.yml, templates/elasticsearch.j2, templates/elasticsearch.yml.j2, templates/init/debian/elasticsearch.j2, templates/init/redhat/elasticsearch.j2, templates/jvm.options.j2, templates/log4j2.properties.j2, templates/systemd/elasticsearch.j2
As requested in #182 a PR for the 5.x branch.
Copied description from #182:
In order to be able to install a Elasticsearch cluster using version 5.0.0, I had to add the following v5.x support (next to the other PRs I submitted today and yesterday):
* **Use log4j2.properties instead of logging.yml** - https://www.elastic.co/guide/en/elasticsearch/reference/5.0/settings.html#logging
* **Add jvm.options** - https://www.elastic.co/guide/en/elasticsearch/reference/master/setting-system-settings.html#es-java-opts
* **Use bootstrap.memory_lock instead of bootstrap.mlockall** - https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-configuration-memory.html#mlockall
* **Get rid of work directory** - https://github.com/elastic/elasticsearch/pull/10672
* **Executable does not accept …
=> Fix es5 issues

tasks/elasticsearch-plugins.yml, tasks/elasticsearch.yml, tasks/xpack/elasticsearch-xpack-install.yml, tasks/xpack/elasticsearch-xpack.yml
As requested in #182 a PR for the 5.x branch.
Copied from #178:
The `plugin` executable for Elasticsearch version 5.0.0, is renamed `elasticsearch-plugin`.
This PR uses the new executable name when `es_version` indicates that version 5 (or higher) is used.
Some other minor plugin-related changes:
* Removed `sed -n '1!p' | cut -d '-' -f2-` as the executable just returns a list of installed plugins (or is this also new in version 5.x?)
* Added task name for 'installed plugins check'
* Result of 'remove plugins' task is stored in `plugin_removed`
Note that I have updated the xpack/* files as well, but this is untested. Since it also contains some shell filters (`tail -n +2`), I would assume it does not work with version 5 as well...
=> Add binary prefix for version 5.x

tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml
The dependency on httplib2 was removed in Ansible 2.1
Resolves #161
=> Remove httplib2

tasks/elasticsearch-Debian.yml
Additional change related to the custom Debian repositories: if no signing key is defined, assume packages are not signed and set apt::allow_unauthenticated=true; conversely, if the signing key is defined, actively set apt::allow_unauthenticated=false regardless of inherited defaults.
=> Allow unauthenticated package installs when es_apt_key is false

tasks/elasticsearch-plugins.yml
When you install a large number of plugins and unstable network - a problem to install a plugin causes a problem in the performance of ansible-playbook.
In this case - the plugin was successfully installed on the second or third run ansible-playbook.
I want to get away from this problem, and make several attempts to install the plugin if it did not happen on the first try.
=> Add retries for install plugins task

.kitchen.yml, README.md, handlers/elasticsearch-templates.yml, handlers/shield/elasticsearch-shield-native.yml, tasks/elasticsearch-Debian.yml
Merges https://github.com/elastic/ansible-elasticsearch/pull/209 with additional fixes for loading templates. Reverts https://github.com/elastic/ansible-elasticsearch/commit/5212c6eb4c84b04b36f5850740809d26d6658c16#diff-7f25ff5bf33de039104c5c59d1709488 and adds additional docs
Removes support for centos 6 and debian 7 testing and 1.x
=> Use api_host and api_port + removal of tests

handlers/elasticsearch-templates.yml
Sticking with the `es_api_host` as the only variable to use for the host in API calls, etc.  `es_api_host ` defaults to `localhost` which is a good default since many elasticsearch configs set `_local_` in `network.host`.
=> Only use es_api_host in API calls since es_config['network.host'] is not a reliable source

handlers/main.yml, tasks/elasticsearch-config.yml, tasks/elasticsearch-service.yml, tasks/main.yml
This PR fixes some issues with the systemd service:
* When service configuration got changed, a `systemctl daemon-reload` is required to refresh the service configuration of systemd
* Do not start the service as task but always use handler. This prevents skipped service restarts when configurations are changed between initial start and the rest of the role.
* Enable service in handler (as the start task is removed). Known issue: the service is not (re)enabled when nothing else changed. I do not think this will ever occur, only situation I can think of, is that the user manually disabled the service and tries to enable it again without changing anything in the configuration/plugins.
=> Fix issues with systemd service

handlers/shield/elasticsearch-shield-native.yml, tasks/xpack/elasticsearch-xpack-activation.yml, tasks/xpack/elasticsearch-xpack-install.yml, tasks/xpack/elasticsearch-xpack.yml, tasks/xpack/shield/elasticsearch-shield-file.yml, test/integration/helpers/serverspec/xpack_spec.rb, test/integration/xpack.yml
- We will support xpack soon, so I think we should able to enable xpack by activating the corresponding license by providing `es_xpack_license`
- Don't log user credential on the cli when adding or updating user password
- Fix a typo when removing plugin
@gingerwizard please review and advice :)
=> Activate elasticsearch license and some fixes

README.md, defaults/main.yml, test/integration/config-2x/serverspec/default_spec.rb, test/integration/multi-2x/serverspec/default_spec.rb, test/integration/package-2x/serverspec/default_spec.rb, test/integration/standard-2x/serverspec/default_spec.rb, test/integration/xpack-2x/serverspec/default_spec.rb
Moves default version to 2.4.3 and doc updates re x-pack.
=> Version change and X-Pack Docs

tasks/xpack/elasticsearch-xpack-install.yml
Ansible 2.2.0 will barf when it hits this task.  It complains about the syntax of unquoted variable. 
The error
```
TASK [elasticsearch : include] *************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "reason": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in '/vagrant/ansible/roles/elasticsearch/tasks/xpack/elasticsearch-xpack-install.yml': line 16, column 23, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- name: Remove {{item}} plugin\n  command: {{es_home}}/bin/plugin remove {{item}}\n                      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when …
```
=> quote interpolated variables in command

templates/elasticsearch.repo
this commit adds support for the `proxy` setting in the yum repo definition. It reuses `es_proxy_host` and `es_proxy_port` from main configuration
=> Adding proxy support for yum repo

README.md
Adding a badge is a nice way to advertise that this repo is available via Ansible-Galaxy.
=> Added badge for Ansible Galaxy

defaults/main.yml, templates/jvm.options.j2
It would be nice to pass custom parameters to JVM used in Elasticsearch. For example:
es_jvm_custom_parameters:
- "-Dcom.sun.management.jmxremote"
It enables us to collect metrics by prometheus jmx exporter via local JVM RMI interface.
=> Ability to add custom jvm options

tasks/xpack/elasticsearch-xpack-install.yml
Without this, the variable x_pack_installed doesn't get registered in check mode, and consequently playbook execution halts on the task "Remove x-pack plugin" which uses it in the when clause.
=> Add check_mode:no to x_pack_installed

tasks/xpack/elasticsearch-xpack-install.yml, tasks/xpack/elasticsearch-xpack.yml
Adding check_mode:no to prevent ansible-playbook failing on missing dict_objects when running with --check.
=> Add check_mode: no to prevent failing in --check mode

.kitchen.yml, defaults/main.yml, tasks/elasticsearch-config.yml, tasks/elasticsearch-plugins.yml, tasks/elasticsearch-scripts.yml, test/integration/config-5x/serverspec/default_spec.rb, test/integration/config.yml, test/integration/helpers/serverspec/config_spec.rb, test/integration/helpers/serverspec/package_spec.rb, test/integration/helpers/serverspec/xpack_spec.rb, test/integration/multi-5x/serverspec/default_spec.rb, test/integration/multi.yml, test/integration/package-5x/serverspec/default_spec.rb, test/integration/package.yml, test/integration/standard-5x/serverspec/default_spec.rb, test/integration/standard.yml, test/integration/xpack-5x/serverspec/default_spec.rb, test/integration/xpack.yml
1. ES is now 5.2.2
2. Plugin diffing now occurs. If you remove or add plugins to the list, they will be uninstalled/installed respectively.
3. Standard and multi test becomes the only idempotent test. Enhanced to install plugins with minor config changes for idempotent test.
4. Config test confirms config changes if run multiple times. It also tests plugins can be removed and added.
5. Package test confirms we can upgrade between minor versions and tests this with respect to plugins.
6. Xpack tests check plugin upgrade between minor versions
7. We now identify the installed plugins with a ls command. Resolves https://github.com/elastic/ansible-elasticsearch/issues/213.
I would suggest we rename tests at some point to reflect their purpose. Standard should be enhanced to test more …
=> Support for plugin diffs + improved testing on minor upgrades + fixes

templates/jvm.options.j2
https://github.com/elastic/elasticsearch/pull/22452
=> Disable the Netty recycler

tasks/java.yml
replace the command with the shell module to check the open jdk.
=> fix the check for the openjdk

tasks/elasticsearch-plugins.yml
* Get (and use) list of plugins that need to be installed
Similar to getting/calculating the list of plugins that need to be removed, except that the `es_plugins` list also can contain additional data.
* Just remove all plugins of the remove list
After determining which plugins need to be removed, the `when` check is not required (anymore)
=> Fix adding of plugins when es_plugins_reinstall is false

README.md
Hello,
There appeared to be duplicate config issue in the samples
sample warnings...
[obalyuk@obalyuk-t450s elk]$ ansible-playbook -i hosts elastic-setup.yml 
[WARNING]: While constructing a mapping from /home/obalyuk/Projects/misc-scripts/ansible/elk/elastic-setup.yml, line 23, column 5, found a duplicate dict key (es_scripts). Using last defined value only.
[WARNING]: While constructing a mapping from /home/obalyuk/Projects/misc-scripts/ansible/elk/elastic-setup.yml, line 23, column 5, found a duplicate dict key (es_templates). Using last defined value only.
[WARNING]: While constructing a mapping from /home/obalyuk/Projects/misc-scripts/ansible/elk/elastic-setup.yml, line 23, column 5, found a duplicate dict key (es_version_lock). Using last defined value only.
=> fixed duplicate configuration in README

.kitchen.yml, Gemfile, Gemfile.lock, README.md, tasks/elasticsearch-plugins.yml, tasks/xpack/elasticsearch-xpack-install.yml, test/integration/helpers/serverspec/standard_spec.rb, test/integration/standard-5x/serverspec/default_spec.rb
A number of changes here:
1. I've updated the gems and testing infrastructure to the latest version.
1. We now remove ansible from all of the provided images and use ansible kitchen's support for installing a specific version -  2.3.2.0
1. Updated the version we test against to 2.3.2.0
1. Changed the proxy specification as per [ this PR](https://github.com/elastic/ansible-elasticsearch/pull/284) from @jdlourenco. I've used the official environment support which simplifies our commands nicely.
1. Standard test now checks for ingest-geoip.
This has been tested locally. Working on new test infrastructure.
=> Proxy Env Fix + New Gems + Testing tweaks

tasks/xpack/security/elasticsearch-security-file.yml, tasks/xpack/security/elasticsearch-security.yml
Fix for #290 
This just moves the x-pack directory creation up one level to be accessible by the `es_role_mapping` tasks which, until now, have incidentally relied on it.
To test this, I've created a separate branch in my repo w/ a separate test because I didn't want to make the call to muddy up the pretty focused set of tests that currently exist.
My test is on the `role-mapping-xpack-dir-test` branch here: https://github.com/rusnyder/ansible-elasticsearch/tree/role-mapping-xpack-dir-test
To test this, you can demonstrate the failure case, patch this PR, then demonstrate success:
```
git clone https://github.com/rusnyder/ansible-elasticsearch elasticsearch
cd elasticsearch
git checkout role-mapping-xpack-dir-test
bundle install
ES_XPACK_LICENSE_FILE=/path/to/license.json bundle exec …
```
=> Moved up the x-pack directory logic to include role_mappings

tasks/main.yml, templates/elasticsearch.repo
Ensure that elasticsearch is started/running even if non of the handlers
are called. Previously, if the host was provisioned correctly, but
elasticsearch was not running the role would not attempt to start it.
This can happen if elasticsearch was killed, or if the previous ansible
run failed prior to running the handlers.
Previously if the proxy host was defined but empty, an invalid proxy was
config was added and the install would fail. This is likely to occur
for instances where you conditionally set the proxy.
=> Ensure elasticsearch is always started and fix yum proxy logic

defaults/main.yml, tasks/elasticsearch-config.yml
be able to override log4j2.properties with custom template using variable es_config_log4j2 as the template path
=> override log4j2.properties with custom template

.kitchen.yml, handlers/main.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml, tasks/elasticsearch-config.yml, tasks/elasticsearch-optional-user.yml, test/integration/helpers/serverspec/issue_test_spec.rb, test/integration/issue-test.yml, test/integration/issue-test/issue-test.yml, test/integration/issue-test/serverspec/default_spec.rb
This PR simplifies the restart logic, relying on the restart handler only. We now notify the handler consistently and remove the additional checks.
This should close the following issues:
https://github.com/elastic/ansible-elasticsearch/issues/305
https://github.com/elastic/ansible-elasticsearch/issues/315
All tests pass locally. 
I have also added issue-test.yml.  This test will not be included in the new automated tests, but allows us to easily test playbooks for user issues. I'll add instructions once we have the automated test suite - users can in theory then issue a PR with a playbook in the test-issue.yml and immediately demonstrate the failure.
@barryib @jpcarey i believe this simplifies restarts significantly.
=> Simpler restart handling + issue-test for recreation of problems

.kitchen.yml, filter_plugins/custom.py, tasks/elasticsearch-parameters.yml, tasks/elasticsearch-template.yml, tasks/main.yml, tasks/xpack/security/elasticsearch-security-file.yml, tasks/xpack/security/elasticsearch-security-native.yml, test/integration/helpers/serverspec/xpack_spec.rb, test/integration/issue-test.yml, test/integration/xpack.yml, vars/main.yml
This aims to fix issue #369.  A couple of problems were identified:
1. We weren't able to set the password for reserved users e.g. kibana or elastic.  This is now possible through the native realm only. Attempting to do this through the file realm is actually an invalid operation in ES. 
**native realm**
For the native realm we query ES to get the list of users as these are subject to change across versions, and then only allow the password to be set on those that are reserved i.e. role changes are ignored.  No changes are allowed to reserved roles at all.  If the user attempts to change a reserved role, or reserved users membership to a role, in the native realm we simply log a warning rather than hard fail. 
**file realm**
We have the similar behaviour in the file realm. This, however, …
=> Fix for issue #369

README.md, defaults/main.yml, templates/init/debian/elasticsearch.j2
Simple, backwards-compatible change, to allow for other timeout values for node startup than the hard coded 10 seconds in Debian SysV init scripts. No other managed startup script/scheme seems to enforce a similar startup timeout, so only changed here.
Motivation: one of my 8 boxes that make up a cluster takes 11 seconds to startup, and the ansible run always fails due to this.
=> Parameterize timeout value for ES startup in Debian SysV init scripts

templates/elasticsearch.yml.j2
the default values are:
- es_enable_xpack: false
- es_xpack_features: ["alerting","monitoring","graph","ml","security"]
With the default values, XPACK is not installed
But the generated elasticsearch.yml contains the XPACK Settings.
Elasticsearch application refuses to start with these unknown settings
=> elasticsearch.yml: xpack settings added only if es_enable_xpack

tasks/elasticsearch-Debian.yml, tasks/elasticsearch-parameters.yml, tasks/elasticsearch-plugins.yml, tasks/elasticsearch-scripts.yml, tasks/elasticsearch-template.yml, tasks/java.yml, tasks/main.yml, tasks/xpack/elasticsearch-xpack-install.yml, tasks/xpack/elasticsearch-xpack.yml, tasks/xpack/security/elasticsearch-security-file.yml, tasks/xpack/security/elasticsearch-security-native.yml, tasks/xpack/security/elasticsearch-security.yml
I've added names to all tasks in relation to issue: 
#402 "Give a name to anonymous set_fact tasks".
=> naming unnamed tasks

tasks/elasticsearch-RedHat.yml
I was getting
`fatal: [redacted_hostname]: FAILED! => {"attempts": 5, "changed": false, "failed": true, "msg": "", "rc": 0, "results": ["elasticsearch-6.2.1-1.noarch providing elasticsearch is already installed"]}`
because „failed” was all the time present in the response.
=> Fix RedHat install - until condition was not correct

tasks/java.yml
promote `update-alternatives` command to run as admin role
I have problem when i tried to run this ansible script to Google Compute Engine
It show below error
```
TASK [elasticsearch : correct java version selected] *****************************************************************************
fatal: [35.186.157.183]: FAILED! => {"changed": false, "failed": true, "msg": "Specified path  does not exist"}
to retry, use: --limit @/.../Projects/ansible-elasticsearch/site.retry
```
After debug, it's because `java_full_path` has empty value because `update-alternatives` got error but hidden by `failed_when: False`
It look like, `update-alternatives` need to run by admin role
=> require admin role to use update-alternatives

test/integration/helpers/serverspec/xpack_spec.rb
This was causing flaky tests because the
order of the users in the test doing `curl -s localhost:9200/_xpack/security/user -u
es_admin:changeMeAgain` is not consistent which caused random failures.
Now if it does fail we will actually know the reason why:
```
security users
should have the elastic user
should have the kibana user (FAILED - 1)
should have the kibana_server user
should have the logstash user
logstash_system access check
should be reported as version 6.2.4
Failures:
1) Xpack Tests security users should have the kibana user
Failure/Error: expect(result['kibana']['username']).to eq('kibana4')
expected: "kibana4"
got: "kibana"
```
The failure output use to look like:
```
Failures:
1) Xpack Tests Command "curl -s localhost:9200/_xpack/security/user -u es_admin:changeMeAgain | …
```
=> Look at the results from the http request instead of checking the md5 hash

test/matrix.yml
This allows us to control and modify the jenkins matrix job via the pull
request flow instead of needing to sync changes in the jenkins
configuration.
I originally added it in the 6.3 support PR with a commit message but I apparently didn't check in the file :S https://github.com/elastic/ansible-elasticsearch/pull/452/commits/c1b83a892f0cac80203b9bc858ae09a1a5f35414
=> Add jenkins test matrix yml definition

.kitchen.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml, tasks/elasticsearch-config.yml, test/integration/helpers/serverspec/config_spec.rb, test/integration/helpers/serverspec/multi_spec.rb, test/integration/helpers/serverspec/oss_upgrade_spec.rb, test/integration/helpers/serverspec/package_spec.rb, test/integration/helpers/serverspec/standard_spec.rb, test/integration/helpers/serverspec/xpack_spec.rb, test/integration/helpers/serverspec/xpack_standard_spec.rb, test/integration/oss-upgrade.yml, test/integration/oss-upgrade/oss-upgrade.yml, test/integration/oss-upgrade/serverspec/default_spec.rb, test/matrix.yml
This PR adds an automated test to make sure that upgrading from elasticsearch without xpack to 6.3 oss works as expected (it wasn't so the fixes are also included in this pr).
Next PR will be making sure the upgrade path from 6.2 oss to 6.3 xpack is also working properly. 
Right now we are testing the following:
6.2 oss -> 6.3 oss (this PR)
6.2 xpack -> 6.3 xpack (the "xpack" test suite does this)
Todo:
6.2 oss -> 6.3 xpack
Once all of the upgrade paths test are in place and 6.3 has been released I'm going to remove the other test suites which aren't really doing to much. The final set of suites will look something like
oss
xpack
oss-upgrade
xpack-upgrade
oss-to-xpack-upgrade
multi
=> Add test for upgrading from previous version of oss to current

tasks/elasticsearch-config.yml
**Elasticsearch version**: `6.3.0`
**Role version**: `6.3.0`
**JVM version** (`java -version`):
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```
Linux hostname 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```
**Ansible version** : 
```
ansible 2.5.5
config file = None
configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```
**Description of the …
=> Fix systemd stat symlink

tasks/elasticsearch-config.yml, tasks/main.yml, tasks/xpack/security/elasticsearch-security.yml
I'm not sure if there are other become statements missing but these were the ones I needed initially ;)
Are these known? I saw at least one in [460](https://github.com/elastic/ansible-elasticsearch/pull/460)
=> add missing become: root

tasks/snapshot-release.yml
The response from the search endpoint is now wrapped in a map with the
packages key.
I haven't updated DNS for the artifacts api, yet.  Aside from merging this after I update DNS, are there any other changes or steps needed here?
=> handle the nested response

test/integration/helpers/serverspec/xpack_spec.rb
This was previously passing because our CI configuration was actually
testing 6.x instead of 5.x. Luckily this is the only problem which
hadn't been caught since this was introduced.
=> Fix the tested path.conf for 5.x

README.md
When comparing `es_config` for master ([L198](https://github.com/elastic/ansible-elasticsearch/commit/571dde5ac2b57294d4becd5da6ca8553438ae6a2?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8L198)) and data nodes([L220](https://github.com/elastic/ansible-elasticsearch/commit/571dde5ac2b57294d4becd5da6ca8553438ae6a2?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8L220)), the order was different. This PR makes it consistent, hence it is easy to compare.
=> Make the order of configs consistent for comparing

tasks/elasticsearch-plugins.yml
this line : 
check_mode: no
ensures that the variable installed_plugins is defined, and the next task can be run in check mode ('undefined variable' instead)
=> add idempotence in check mode for plugins

tasks/elasticsearch-parameters.yml
Instead of using
`result|version_compare` use `result is version_compare`.
=> Using tests as filters is deprecated

tasks/elasticsearch-Debian.yml, vars/main.yml
The old URL yields a 404. This should work for both Debian and Red Hat.
=> Fix package download URL

tasks/compatibility-variables.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml, test/integration/helpers/serverspec/shared_spec.rb
Before only going from the standard package to oss was supported. Now
this works properly in both directions.
Fixes: #520
=> Allow switching between oss and standard packages

tasks/elasticsearch-Debian.yml
If a variable is set in Ansible, there is no way to unset it ever again, i.e. setting `es_apt_key: null` or `es_apt_key: ~` do not work.
Since this value is set in `defaults/main.yml` we have to perform a boolean check on the string.
=> Allow not installing Elasticsearch deb repository key

tasks/java.yml
This PR is related to this issue.
https://github.com/elastic/ansible-elasticsearch/issues/525
This problem is happened in --check mode, because in check mode ignored test for java_full_path and does not register it.
So this PR changed to execute in check mode and register java_full_path.
=> Execute java version check in check mode

templates/systemd/elasticsearch.j2
User might be interested in separating ephemeral and persistent data.
Among others, this can be done by putting `data_dir` on another disk.
When doing that in cloud environments via [`cloud-init`](https://github.com/cloud-init/cloud-init) or [`waagent`](https://github.com/Azure/WALinuxAgent) you need to time the service start to _after_ the necessary devices are mounted, otherwise a low run-level can result in trying to start the service before all data/mounts is/are available.
This PR adds [systemd's `RequiresMountsFor`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#RequiresMountsFor=) directive for the corresponding folders.
=> Use systemd's RequiresMountsFor

tasks/elasticsearch-Debian-version-lock.yml
Uses module dpkg_selections to hold elasticsearch version on debian.
=> Use dpkg_selections to lock elasticsearch version

tasks/elasticsearch-plugins.yml
Preventing errors like:
```
TASK [elastic.elasticsearch : Install elasticsearch plugins] *******************
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ item.plugin in plugins_to_install }}
fatal: [default]: FAILED! => {"msg": "The conditional check ''ERROR' in plugin_installed.stdout' failed. The error was: error while evaluating conditional ('ERROR' in plugin_installed.stdout): Unable to look up a name or access an attribute in template string ({% if 'ERROR' in plugin_installed.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"}
to retry, use: --limit @/tmp/ansible/site.retry
```
=> backporting from master to work with ansible 2.7.4

tasks/elasticsearch-Debian.yml, tasks/java.yml
Hey guys,
it was impossible to run the `--check` mode on top of the role.
(Please refer to the Ansible docs for details at: https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html)
The PR adds a micro tweak to properly `register` variables when in the check_mode.
=> make playbook (tested for debians) compatible with the  mode

tasks/main.yml
Hi,
I did like to replace usage of pause module by sleep command.
Because pause module is not usable in free strategy it will raise an error:
ERROR! The 'pause' module bypasses the host loop, which is currently not supported in the free strategy and would instead execute for every host in the inventory list.
No side effect excepted.
>The error appears to have been in '<masked>elasticsearch/tasks/main.yml': line 75, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
>The offending line appears to be:
>If playbook runs too fast, Native commands could fail as the Native Realm is not yet up
>- name: Wait 15 seconds for the Native Relm to come up
>  ^ here
=> Use sleep command in remplacement of pause

defaults/main.yml, tasks/compatibility-variables.yml, tasks/xpack/elasticsearch-xpack.yml, tasks/xpack/security/elasticsearch-security.yml, templates/elasticsearch.yml.j2, templates/init/debian/elasticsearch.j2, templates/init/redhat/elasticsearch.j2, templates/log4j2.properties.j2, templates/systemd/elasticsearch.j2
Previously, each of the calls generated a warning: "Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be removed in version 2.9.".
=> Refactor deprecated version_compare filter calls

README.md
In #538 it was discovered that recent versions of the ansible galaxy
command will fail if there aren't semver compatible releases in the
history.
The error says:
> Please contact the role author to resolve versioning conflicts, or
> specify an explicit role version to install.
Removing the old releases is not such a great idea so instead updating
the install command is the best option.
Fixes: #538
=> Update readme to include versioned install command

.ci/jobs/defaults.yml, .ci/jobs/elastic+ansible-elasticsearch+master.yml, .ci/jobs/elastic+ansible-elasticsearch+pull-request.yml
Add JJBB job definitions to the repo so they can be managed here.
Modified jobs so they will auto-generate the `inject-passwords` section
containing `VAULT_ROLE_ID`, `VAULT_SECRET_ID` and `VAULT_ADDR`.
=> [ci] add JJBB job definitions

tasks/elasticsearch-config.yml, tasks/snapshot-release.yml, tasks/xpack/security/elasticsearch-security-file.yml, tasks/xpack/security/elasticsearch-security-native.yml, tasks/xpack/security/elasticsearch-security.yml
Those look ok to add the check_mode:no flag, since not changing anything in the system.
But ultimately all the `register:` should probably just go this way or another I'm afraid, for ultimate idempotence of the role.
=> add a few more 'check_mode:no' props for compatiblity with --check

defaults/main.yml, tasks/compatibility-variables.yml, templates/elasticsearch.repo
Some popular artifact caches (e.g. Artifactory) do not provide `HTTP CONNECT` endpoints and thus aren't supported by `es_proxy_host` and `es_proxy_port`.  This patch templates out the scheme and authority components (i.e. "https://artifacts.elastic.co" ) of the apt and yum repo URLs to accommodate the use of such artifact caches.
=> Template out the base of repo URLs

.kitchen.yml
Jessie backport repos have been removed from debian mirrors and moved to archive mirrors (cf. https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html). We also need to disable validity checks as this repo is no more updated (https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository)
=> [test] fix debian-8 provisioning in kitchen tests

Gemfile.lock
This should fix vulnerability on ffi and rubyzip dependencies (cf. https://nvd.nist.gov/vuln/detail/CVE-2018-1000544 and https://nvd.nist.gov/vuln/detail/CVE-2018-1000201)
=> [gem] update dependencies

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml, docs/multi-instance.md
should fix https://github.com/elastic/ansible-elasticsearch/issues/554
=> release 7.1.1 version

README.md
Use correct role name from ansible galaxy
=> Docs: Fix name of elasticsearch ansible role

tasks/elasticsearch-parameters.yml, tasks/xpack/security/elasticsearch-security-file.yml, tasks/xpack/security/elasticsearch-security-native.yml
In Python2, the dict.keys(), dict.values(), and dict.items() methods returns a list. Jinja2 returns that to Ansible via a string representation that Ansible can turn back into a list. In Python3, those methods return a dictionary view object.
resource: https://docs.ansible.com/ansible/2.4/playbooks_python_version.html#dictionary-views
Fix https://github.com/elastic/ansible-elasticsearch/issues/570
=> fix ''dict object has no attribute dict_keys" issue with python3

tasks/elasticsearch-template.yml, tasks/xpack/security/elasticsearch-xpack-activation.yml
Related: #576
This is needed when using security for 6.x. All other http requests
still have this parameter added.
=> Add back in force_basic_auth for all http requests

README.md, defaults/main.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml
Sometimes, instances can't be access to public repository on internet. We must be able to use a private repository already deployed on instance.
=> Add option for disable the addition of official repository

docs/multi-instance.md
Should fix https://github.com/elastic/ansible-elasticsearch/issues/581
=> add doc for migration with data move

tasks/elasticsearch-Debian-version-lock.yml, tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat-version-lock.yml, tasks/elasticsearch-RedHat.yml
Fix for https://github.com/elastic/ansible-elasticsearch/issues/499
=> Removing package version hold when `es_version_hold: false`

.github/issue_template.md, .github/stale.yml
This PR add [Probot](https://probot.github.io/) configuration to manage stale issues/PR:
- Issues / PR will be marked as stale (with a `triage/stale` label) after 90 days without any activity.
- Stale issues / PR will be closed automatically after 30 days without any activity.
=> Add probot config to manage stale issues/pr

README.md
We regularly receive requests about releasing new versions of this Ansible role to allow deployment of new Elasticsearch versions.
While we should definitively improve our release process to follow Elasticsearch release, we need also to clarify the fact that in most cases, deploying a different version can  be done easily by overriding [`es_version`](https://github.com/elastic/ansible-elasticsearch/blob/master/defaults/main.yml#L2) variable.
=> [doc] describe how to select a different elasticsearch version

tasks/elasticsearch-ssl.yml
bool ansible filter can only be used for strings matching "true" or "false"
Fix #639
=> fix when condition for es_ssl_certificate_authority

README.md
... to fix broken links in Ansible Galaxy.
Fixes #656
@jmlrt I linked to master, which seems like the most easy to maintain, but in theory it could lead to outdated links again in the future if the version on Ansible Galaxy is different than master.
=> switched relative URLs to absolute URLs 

tasks/elasticsearch-RedHat-version-lock.yml
fixes error when running `ansible-playbook` with `--check`
Error message was:
`The conditional check 'es_version_locked.stdout|int > 0' failed. The error was: error while evaluating conditional (es_version_locked.stdout|int > 0): 'dict object' has no attribute 'stdout'`
=> fix check mode

defaults/main.yml, templates/elasticsearch.j2
This PR introduces a variable called `es_java_home`, which defaults to an empty string.  If set to a non-empty string, that string is used to set the JAVA_HOME environment variable in the default config file (via the `templates/elasticsearch.j2` template).
If `es_java_home` is not changed from its default, the file generated from the template is unchanged.  That is to say, this change should be entirely backwards-compatible.
=> Introduce es_java_home variable to allow setting JAVA_HOME 

README.md
Nodes won't be able to join the cluster if the port is specified in `initial_master_nodes`.  
The `cluster.initial_master_nodes` setting is used to determine the identities of the subset of master-eligible nodes that participate in the bootstrapping process.
See ES documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-discovery-bootstrap-cluster.html).
=> Removed port from initial_master_nodes setting

meta/main.yml
This is required following 20d2a8f as `version` replace `version_compare` in Ansible 2.5.
=> [meta] bump minimal ansible version to 2.5.0

README.md, defaults/main.yml, templates/jvm.options.j2
- Update JVM options to include changes made in elastic/elasticsearch#49123
- Add a new variable to allow overriding heap dump path (replace #668)
=> Update jvm options with default values for 7.6.0

tasks/elasticsearch-RedHat.yml, tasks/elasticsearch-parameters.yml
Running ansible in check mode gave errors on 2 tasks.
fixed those
=> Fixed running ansible in check mode

.ci/jobs/defaults.yml, .ci/jobs/elastic+ansible-elasticsearch+master.yml
This PR add Slack notifications to Elastic Release team Slack channel for [elastic+ansible-elasticsearch+master](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+master/) test job.
=> [meta] add slack notifications to CI jobs

.ci/jobs/elastic+ansible-elasticsearch+master.yml
This commit adds a new auth-token-credential-id entry in addition of auth-token-id for slack token.
This is due to a bug in JJB which requires having both entries to prevent having an empty authTokenCredentialId in job config.xml (https://storyboard.openstack.org/#!/story/2007953).
=> [meta] add auth-token-credential-id entry for slack

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
* 7.8.1 as default version
* 6.8.11 as 6.x tested version
| PR                                                                | Author                                 | Title                                    |
|-------------------------------------------------------------------|----------------------------------------|------------------------------------------|
| [#701](https://github.com/elastic/ansible-elasticsearch/pull/701) | [@suramon](https://github.com/suramon) | Fix running ansible in check mode        |
| [#703](https://github.com/elastic/ansible-elasticsearch/pull/703) | [@anisf](https://github.com/anisf)     | Add amazonlinux2 support                 |
| [#705](https://github.com/elastic/ansible-elasticsearch/pull/705) | [@andzs](https://github.com/andzs)     | Use sudo for …
=> 7.8.1 release

tasks/xpack/security/elasticsearch-security.yml
Run the password through the `quote` filter rather than quoting it manually.
Close #711
=> Properly quote password in shell command

defaults/main.yml, templates/elasticsearch.j2
Elasticsearch requires its temp directory to be mounted as executable (see [executable-jna-tmpdir](https://www.elastic.co/guide/en/elasticsearch/reference/current/executable-jna-tmpdir.html)).  However, the CIS guidelines (e.g., [CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v2.1.1](http://www.itsecure.hu/library/image/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v2.1.1.pdf), 1.1.5) recommend mounting /tmp with noexec.  Therefore, users of this ansible role may have reason to set elasticsearch's temp dir to a non-default location.
(The elasticsearch environment variable ES_TMPDIR gets set to /tmp by default.  This PR preserves this default behavior.)
=> add ansible var for ES_TMPDIR env var

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
* 7.9.1 as default version
| PR                                                                | Author                                 | Title                                    |
|-------------------------------------------------------------------|----------------------------------------|------------------------------------------|
| [#701](https://github.com/elastic/ansible-elasticsearch/pull/701) | [@suramon](https://github.com/suramon) | Fix running ansible in check mode        |
| [#703](https://github.com/elastic/ansible-elasticsearch/pull/703) | [@anisf](https://github.com/anisf)     | Add amazonlinux2 support                 |
| [#705](https://github.com/elastic/ansible-elasticsearch/pull/705) | [@andzs](https://github.com/andzs)     | Use sudo for users migration from <6.3.0 |
=> 7.9.1 release

tasks/main.yml
I am proposing a fix for issue #710. By specifying run_once: True for all tasks related to the native user, roles, and license API. The role can avoid unnecessary API calls as well as fixing the issue. I used the same playbook as in the issue report. The ansible log [here](http://sprunge.us/tJ6xZY) shows a successful run.
This could be further 'optimized' by delegating all the API calls to localhost. However, this would require the es_api_url to be accessible from the ansible machine which may not always be the case.
=> Use run_once for api related tasks

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml
* 7.9.3 as default version.
* 6.8.13 as 6.x tested version
| [#727](https://github.com/elastic/ansible-elasticsearch/pull/727) | [@smutel](https://github.com/smutel) | Add an option to not upload SSL/TLS certs  |
| [#726](https://github.com/elastic/ansible-elasticsearch/pull/726) | [@vielfarbig](https://github.com/vielfarbig) | Add note to only using es_data_dirs and es_log_dir for customizing th…  |
=> 7.9.3 release

docs/ssl-tls-setup.md
Just add some part in the documentation to help user changing the password of default user (elastic).
=> Improve the documentation for TLS

.kitchen.yml, README.md, test/matrix.yml
Add support for CentOS-8
Closes https://github.com/elastic/ansible-elasticsearch/issues/737
=> Support CentOS 8

CHANGELOG.md, README.md, defaults/main.yml
* 7.10.1 as default version.
| [#747](https://github.com/elastic/ansible-elasticsearch/pull/747) | [@fourstepper](https://github.com/fourstepper) | Fix idempotency for both supported CentOS versions  |
| [#744](https://github.com/elastic/ansible-elasticsearch/pull/744) | [@v1v](https://github.com/v1v) | Support CentOS 8  |
| [#736](https://github.com/elastic/ansible-elasticsearch/pull/736) | [@jmlrt](https://github.com/jmlrt) | Fix test-kitchen net-scp-error  |
=> 7.10.1 release

README.md
This commit fix the Ansible Galaxy install command to use the new
versioning implemented in 7.10.1 release.
ansible-beats tags are now prefixed by v which makes Ansible Galaxy
versions also including this prefix.
Fix #750
=> [meta] fix ansible galaxy install command

tasks/java.yml
This commit fix the command to get Java install path when the system has
multiple java installed
Fix #721
=> Fix java install path when system has multiple java

.ci/jobs/defaults.yml, .ci/jobs/elastic+ansible-elasticsearch+master.yml, .ci/jobs/elastic+ansible-elasticsearch+pull-request.yml
This commit fix the test job templates following #760.
- add VERSION parameter for 7.x jobs
- move axis to jobs templates
=> [meta] fix jobs template following #760

README.md, tasks/xpack/security/elasticsearch-security.yml
Add support to add, update and delete `elasticsearch.keystore` entries.
Obsoletes #685
Fix #684
=> Ad support for elasticsearch-keystore entries

README.md, tasks/elasticsearch-parameters.yml, test/matrix.yml
This commit is removing the option to install Elasticsearch OSS
distribution for version >= 7.11.0.
This is due to Elasticsearch recent license change.
See https://www.elastic.co/blog/licensing-change for more details.
- Add notice to breaking changes and update documentation
- Fail the deployment if trying to install OSS >= 7.11.0
- Remove OSS tests for 7.x except the upgrade test from last OSS version
to default distribution
=> Remove OSS support for version >= 7.11.0

tasks/xpack/security/elasticsearch-security-native.yml
This commit fix "List Native Roles" task with Elasticsearch 7.11.0+
by removing the unused [`body_format`](https://docs.ansible.com/ansible/2.9/modules/uri_module.html#parameter-body_format) parameter from `uri` module.
This parameter isn't used with a GET method but make request fail with
`request [GET /_security/role] does not support having a body` error
with Elasticsearch 7.11.0+.
=> Fix "list native roles" task

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml
* 7.11.1 as default version.
* 6.8.14 as 6.x tested version
| PR                                                                | Author                                                       | Title                                          |
|-------------------------------------------------------------------|--------------------------------------------------------------|------------------------------------------------|
| [#760](https://github.com/elastic/ansible-elasticsearch/pull/760) | [@jmlrt](https://github.com/jmlrt)                           | Add dedicated CI jobs for 6.x                  |
| [#761](https://github.com/elastic/ansible-elasticsearch/pull/761) | [@rubarclk](https://github.com/rubarclk)                     | Fix Elasticsearch 7.x deb url                  |
| …
=> 7.11.1 release

README.md
=> Fix README.md Multi Node Server Installations

tasks/elasticsearch-Debian.yml, tasks/elasticsearch-RedHat.yml, vars/Debian.yml, vars/RedHat.yml
* Fix commit fix the deb package url for Elasticsearch 6.x
* Fix commit fix the rpm package url for Elasticsearch 6.x and 7.x
* Download deb package directly using `apt` module
* Use new ansible syntax
Fix #781
=> Fix deb and rpm url

templates/elasticsearch.j2
This commit set `ES_JAVA_HOME` environment variable instead of
`JAVA_HOME` when `es_java_home` environment variable is used.
See https://github.com/elastic/elasticsearch/issues/68848 for more
context.
=> Use ES_JAVA_HOME instead of JAVA_HOME

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml
* 7.12.0 as default version.
* 6.8.15 as 6.x tested version
| [#789](https://github.com/elastic/ansible-elasticsearch/pull/789) | [@jmlrt](https://github.com/jmlrt) | Use ES_JAVA_HOME instead of JAVA_HOME  |
| [#788](https://github.com/elastic/ansible-elasticsearch/pull/788) | [@jmlrt](https://github.com/jmlrt) | Fix deb and rpm url  |
| [#784](https://github.com/elastic/ansible-elasticsearch/pull/784) | [@jmlrt](https://github.com/jmlrt) | [meta] fix changelog after 7.11.2 release  |
=> 7.12.0 release

tasks/elasticsearch-plugins.yml
In check mode Ansible is actually not going to execute the command from the `Install elasticsearch plugins` task.
https://github.com/elastic/ansible-elasticsearch/blob/4f01bc74a079c726a5045bed5595273fbe2d2bc0/tasks/elasticsearch-plugins.yml#L66-L80
Thus, the `rc` parameter is not set resulting in a failed execution. My suggestion would be to default the parameter to `0`, if it is not set. This allows the role to be run in check mode as well.
Alternatively, it would be possible to add
```yml
ignore_errors: "{{ ansible_check_mode }}"
```
to the task. But I thought the submitted solution might be cleaner.
Closes #786
=> Stop plugin install to fail in check mode

CHANGELOG.md, README.md, defaults/main.yml
* 7.12.1 as default version.
| [#793](https://github.com/elastic/ansible-elasticsearch/pull/793) | [@jmlrt](https://github.com/jmlrt) | [meta] update ubuntu-1804 during kitchen provisioning  |
| [#787](https://github.com/elastic/ansible-elasticsearch/pull/787) | [@tobiashuste](https://github.com/tobiashuste) | Stop plugin install to fail in check mode  |
=> 7.12.1 release

README.md, test/matrix-6x.yml, test/matrix.yml
This commit removes the support of Ubuntu 14.04. This distribution is
EOL since April 30th 2019 and CI tests are failing because apt
repositories aren't available anymore.
=> Remove Ubuntu 14.04 support

tasks/main.yml
command necessarily causes a change on each invocation breaking idempotency, wait_for accomplishes the same goal without the change
=> idempotently wait for native realm to come up

README.md
This commit adds a warning message to the README to
notify users that the role will be deprecated.
=> Add warning message about 8.x versions

README.md, test/matrix-6x.yml, test/matrix.yml
This commit removes CentOS 8 tests. These tests are now failing because
CentOS 8 is now EOL and it's repositories have been archived.
Source: https://forums.centos.org/viewtopic.php?f=54&t=78708
=> Remove CentOS 8 tests

CHANGELOG.md, README.md, defaults/main.yml
* 7.17.0 as default version.
| [#845](https://github.com/elastic/ansible-elasticsearch/pull/845) | [@jmlrt](https://github.com/jmlrt) | Remove CentOS 8 tests  |
=> 7.17.0 release
