templates/init/debian/elasticsearch.j2

https://github.com/elastic/elasticsearch/pull/16718
Fixes #69

Merged debian init script changes from elasticsearch

---

.gitignore
tasks/elasticsearch-plugins.yml
tasks/elasticsearch-templates.yml

Removed bare variables

---

.gitignore
.kitchen.yml
Gemfile.lock
README.md
handlers/main.yml

Includes:
Gem lock file
Default to dliappis images

Build improvements

---

defaults/main.yml
tasks/main.yml

Changes merged from https://github.com/elastic/ansible-elasticsearch/pull/107

107 changes

---

README.md
defaults/main.yml
tasks/elasticsearch-Debian.yml

Per discussion [here](https://github.com/elastic/ansible-elasticsearch/pull/100)

Support for downgrade of packages on debian + doc updates

---

meta/main.yml

Set ansible galaxy min version to `2.0`

---

handlers/main.yml
tasks/elasticsearch-config.yml

Restart on config change

---

tasks/elasticsearch-parameters.yml

Conditional for checking if shield is in the feature list, did not work.

---

.kitchen.yml
tasks/elasticsearch-Debian.yml
tasks/elasticsearch-RedHat.yml

Includes https://github.com/elastic/ansible-elasticsearch/pull/204

Ansible test update + 202

---

.kitchen.yml
tasks/elasticsearch-Debian.yml

Includes https://github.com/elastic/ansible-elasticsearch/pull/146
Requires ansible version 2.10.  We now test against 2.20

Allows unauthenticated repos

---

.kitchen.yml
tasks/elasticsearch-Debian.yml

Merges https://github.com/elastic/ansible-elasticsearch/commit/61bb156dbe77b09f28f5a07c6396b00e6b30a4f1

Plugin Retry

---

.kitchen.yml
README.md
handlers/elasticsearch-templates.yml
handlers/shield/elasticsearch-shield-native.yml
tasks/elasticsearch-plugins.yml

Merges fixes from @vegar as well as issue preventing plugin install on redhat

Fix issues with systemd

---

meta/main.yml

Correction we need 2.1.2 not 2.1.0

Min version of ansible corrected

---

.gitignore
tasks/elasticsearch-Debian-version-lock.yml
tasks/java.yml

Backport of https://github.com/elastic/ansible-elasticsearch/pull/254 to master

Idempotent Fix

---

README.md

Reverts elastic/ansible-elasticsearch#304 until CLA signing is clarified

Revert "fix version and add missing whitespace"

---

.gitignore
README.md
elasticsearch.iml

merges in https://github.com/elastic/ansible-elasticsearch/pull/266 and cleans up some comments.

Clean up .gitinore and remove .iml file

---

.kitchen.yml
tasks/java.yml

Cherry-picked from 946d89ac74c85801a03b30b30d24d0b0b5968caf

Idempotent tests - Make java install idempotent

---

.kitchen.yml
files/logging/log4j2.properties.custom.j2
tasks/xpack/security/elasticsearch-xpack-activation.yml
test/integration/config.yml
test/integration/helpers/serverspec/config_spec.rb
test/integration/helpers/serverspec/standard_spec.rb
test/integration/helpers/serverspec/xpack_spec.rb
test/integration/xpack.yml

Tests the existence of a custom log4j file - functionality added under https://github.com/elastic/ansible-elasticsearch/pull/347
Additionally fixes issues with license registration on x-pack.

Xpack activation fix + testing custom log4j file

---

README.md

Dependency on jmspath

---

test/integration/config.yml
test/integration/helpers/serverspec/config_spec.rb

Complements https://github.com/elastic/ansible-elasticsearch/pull/308 with a quick test

Simple test for LimitNPROC

---

filter_plugins/custom.py

- Change basestring by str to make it python3 compatible

Change basestring by str to make it python3 compatible

---

tasks/xpack/security/elasticsearch-security-native.yml
tasks/xpack/security/elasticsearch-security.yml
test/integration/issue-test.yml

Fixes https://github.com/elastic/ansible-elasticsearch/issues/368 with better checking that vars are defined.

Fix for issue 368

---

tasks/elasticsearch-plugins.yml

The changes in the master branch also work for the 2.x branch and fix (some) idempotent-related issues.
(Note that this PR also include the changes of #271!)

Bring plugin handling up to date with master branch

---

tasks/main.yml
tasks/xpack/security/elasticsearch-security.yml
tasks/xpack/security/elasticsearch-xpack-activation.yml

This change fixes failing conditionals that could be triggered by having xpack enabled but not having security in es_xpack_features.

Fix conditionals introduced in #412 and others

---

.kitchen.yml
Makefile
README.md
defaults/main.yml
tasks/compatibility-variables.yml
tasks/elasticsearch-Debian.yml
tasks/elasticsearch-RedHat.yml
tasks/elasticsearch-plugins.yml
tasks/main.yml
tasks/snapshot-release.yml
tasks/xpack/elasticsearch-xpack.yml
tasks/xpack/security/elasticsearch-security-file.yml
tasks/xpack/security/elasticsearch-security.yml
templates/elasticsearch.repo
test/integration/config.yml
test/integration/helpers/serverspec/config_spec.rb
test/integration/helpers/serverspec/multi_spec.rb
test/integration/helpers/serverspec/package_spec.rb
test/integration/helpers/serverspec/standard_spec.rb
test/integration/helpers/serverspec/xpack_spec.rb
test/integration/helpers/serverspec/xpack_standard_spec.rb
test/integration/issue-test.yml
test/integration/multi.yml
test/integration/package.yml
test/integration/standard.yml
test/integration/xpack-standard.yml
test/integration/xpack.yml
vars/main.yml

This is the baseline to get the current integration tests passing. A follow up PR is coming with
* Modifications to the testing suite (now controlled inside this repo instead of in Jenkins)
* Documentation updates
* Adding a changelog.md to make it easier to keep track of changes.

Initial 6.3 support

---

tasks/elasticsearch-Debian-version-lock.yml
tasks/elasticsearch-RedHat-version-lock.yml

Add version lock to the correct package name

---

tasks/elasticsearch-RedHat.yml

- issue: https://github.com/elastic/ansible-elasticsearch/issues/483

es_allow_downgrades parameter is ignoring yum

---

tasks/java.yml

Bug was reported in discuss in thread https://discuss.elastic.co/t/need-help-running-ansible-playbook-to-install-elastic-search/146238

Only use the first found java version if there are multiple installed

---

tasks/elasticsearch-RedHat.yml

@eRadical thanks for https://github.com/elastic/ansible-elasticsearch/pull/423

BACKPORTED: Fix RedHat install - until condition was not correct

---

README.md

Closes elastic/ansible-elasticsearch#496

Document es_use_repositoruy and es_custom_package_url

---

tasks/compatibility-variables.yml
tasks/elasticsearch-template.yml

The conditional for unauthenticated uploading of templates would always run regardless of whether the templates files had changed or not.

Fix template conditional

---

tasks/elasticsearch-template.yml

use the same task for template install with and without authentication

[templates] simplify template install task

---

docs/multi-instance.md
tasks/elasticsearch-parameters.yml
templates/elasticsearch.yml.j2
test/integration/xpack-upgrade.yml
test/integration/xpack.yml

- strip spaces to avoid wrong indent => fix https://github.com/elastic/ansible-elasticsearch/pull/563
- remove http.port recommendation => fix https://github.com/elastic/ansible-elasticsearch/issues/571
- fix variables names => fix https://github.com/elastic/ansible-elasticsearch/issues/574

Bunch of small fixes

---

files/systemd/elasticsearch_override.conf
tasks/elasticsearch-config.yml
tasks/elasticsearch-parameters.yml
vars/main.yml

This PR fixes https://github.com/elastic/ansible-elasticsearch/issues/585
@jmlrt  I guess I respected your recommendations.

Set limitMEMLOCK for OS using systemd

---

.github/stale.yml

[botelastic] fix probot newlines

---

filter_plugins/custom.py

does what it says on the tin
related to #616

[python] fix AttributeError + format code with black

---

handlers/main.yml

does what it says on the tin
fix #498

use systemd ansible module for daemon-reload

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

7.4.1 release

---

helpers/bumper.py

Add script to bump Elasticsearch versions before release

add bumper script

---

.kitchen.yml
README.md
defaults/main.yml
helpers/bumper.py

Update Elasticsearch default versions:
- 6.8.4 => 6.8.5
- 7.4.1 => 7.4.2

bump elasticsearch to 6.8.5 and 7.4.2

---

CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py
templates/jvm.options.j2

7.5.0 Release

---

README.md
defaults/main.yml
tasks/main.yml

set templates task to run only if es_templates is true

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

7.5.1 release

---

README.md
tasks/elasticsearch-plugins.yml
templates/elasticsearch.j2

add proxy options to ES_JAVA_OPTS when defined with es_proxy_host

---

.ci/jobs/elastic+ansible-elasticsearch+master.yml
.ci/jobs/elastic+ansible-elasticsearch+pull-request.yml

Bump ruby used for kitchen tests from 2.3.0 to 2.5.7

[ci] bump ruby to 2.5.7

---

CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

7.6.0 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

7.6.1 release

---

tasks/xpack/security/elasticsearch-security-file.yml
tasks/xpack/security/elasticsearch-security.yml

Refactor security task files in favor of multi-line format

Update security task files

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

7.6.2 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

* 7.7.0 as default version
* 6.8.9 as 6.x tested version

7.7.0 release

---

tasks/elasticsearch-config.yml
templates/override.conf.j2

https://github.com/elastic/ansible-elasticsearch/issues/683

Support limitnofile with systemd

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

* 7.7.1 as default version
* 6.8.10 as 6.x tested version
| PR                                                                | Author                                             | Title                            |
|-------------------------------------------------------------------|----------------------------------------------------|----------------------------------|
| [#693](https://github.com/elastic/ansible-elasticsearch/pull/693) | [@jurim76](https://github.com/jurim76)             | Fix typo                         |
| [#697](https://github.com/elastic/ansible-elasticsearch/pull/697) | [@ballesterosam](https://github.com/ballesterosam) | Support limitnofile with systemd |

7.7.1 release

---

CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

* 7.8.0 as default version
| PR                                                                | Author                             | Title                          |
|-------------------------------------------------------------------|------------------------------------|--------------------------------|
| [#653](https://github.com/elastic/ansible-elasticsearch/pull/653) | [@jmlrt](https://github.com/jmlrt) | Fix Xpack features refactoring |
| [#699](https://github.com/elastic/ansible-elasticsearch/pull/699) | [@jmlrt](https://github.com/jmlrt) | Add Debian 10 support          |

7.8.0 Release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml
helpers/bumper.py

* 7.9.0 as default version
* 6.8.12 as 6.x tested version

7.9.0 release

---

README.md
tasks/xpack/security/elasticsearch-security-native.yml

fix some typos

---

CHANGELOG.md
README.md
defaults/main.yml

* 7.10.0 as default version.
| [#742](https://github.com/elastic/ansible-elasticsearch/pull/742) | [@jmlrt](https://github.com/jmlrt) | convert custom filter to python3  |
| [#741](https://github.com/elastic/ansible-elasticsearch/pull/741) | [@jmlrt](https://github.com/jmlrt) | [meta] clean deprecated bumper script  |
| [#740](https://github.com/elastic/ansible-elasticsearch/pull/740) | [@jmlrt](https://github.com/jmlrt) | fix some typos  |
| [#728](https://github.com/elastic/ansible-elasticsearch/pull/728) | [@smutel](https://github.com/smutel) | Improve the documentation for TLS  |
| [#739](https://github.com/elastic/ansible-elasticsearch/pull/739) | [@0xflotus](https://github.com/0xflotus) | fix: small error  |

7.10.0 release

---

CHANGELOG.md
README.md
defaults/main.yml

7.10.2 release

---

.ci/jobs/elastic+ansible-elasticsearch+pull-request-6x.yml

This commit fix PR test job for 6.x following #762.

[meta] fix again jjbb template for jenkins jobs

---

CHANGELOG.md
README.md
defaults/main.yml

7.11.2 release

---

tasks/elasticsearch-parameters.yml

Fails deployment when using tls without security

---

CHANGELOG.md
README.md
defaults/main.yml

7.13.2 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

* 7.13.3 as default version.
* 6.8.17 as 6.x tested version
| [#800](https://github.com/elastic/ansible-elasticsearch/pull/800) | [@chuckmilam](https://github.com/chuckmilam) | Minor correction for readability.  |

7.13.3 release

---

CHANGELOG.md
README.md
defaults/main.yml

7.13.4 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

* 7.14.0 as default version.
* 6.8.18 as 6.x tested version

7.14.0 release

---

CHANGELOG.md
README.md
defaults/main.yml

7.15.0 release

---

.kitchen.yml

This entry is already present in line 5.

Remove duplicate entry from YAML

---

CHANGELOG.md
README.md
defaults/main.yml

7.16.0 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

Manually opening PR that somewhat failed opening via automation.

7.16.1 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

* 7.16.2 as default version.
* 6.8.22 as 6.x tested version

7.16.2 release

---

.kitchen.yml
CHANGELOG.md
README.md
defaults/main.yml

* 7.16.3 as default version.
* 6.8.23 as 6.x tested version

7.16.3 release
